import{S as p,a as m,i as n}from"./assets/vendor-DY53avbb.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const d=new p(".gallery .gallery-link",{captionsData:"alt",captionDelay:250});function f(o){const t=o.map(({largeImageURL:i,webformatURL:s,tags:e,likes:r,views:a,comments:c,downloads:u})=>`<li class="gallery-item">
  <a class="gallery-link" href="${i}">
    <img class="gallery-image" src="${s}" alt="${e}"/>
  </a>
  <div class="info">
    <p class="info-item"><b>Likes</b><span>${r}</span></p>
    <p class="info-item"><b>Views</b> <span>${a}</span></p>
    <p class="info-item"><b>Comments</b> <span>${c}</span></p>
    <p class="info-item"><b>Downloads</b> <span>${u}</span></p>
  </div>
</li>`).join("");document.querySelector(".gallery").innerHTML=t,d.refresh()}function y(){document.querySelector(".gallery").innerHTML=""}function g(){document.querySelector(".loader-wrapper").classList.remove("is-hidden")}function l(){document.querySelector(".loader-wrapper").classList.add("is-hidden")}const h="56396197-05fcd5e3b9536b865c8ea6b88";function b(o){return m.get("https://pixabay.com/api/",{params:{key:h,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}})}const L={galleryEl:document.querySelector(".gallery"),formEl:document.querySelector(".form"),loaderEl:document.querySelector(".loader-wrapper")};L.formEl.addEventListener("submit",S);function S(o){o.preventDefault();const t=o.target.elements[0].value.trim();if(!t){n.show({title:"Sorry, ",message:"there are no images matching your search query. Please try again!",position:"topRight"});return}y(),g(),b(t).then(i=>{if(l(),i.data.hits.length===0){n.error({title:"Sorry, ",message:"there are no images matching your search query. Please try again!",position:"topRight"});return}f(i.data.hits)}).catch(i=>{l(),n.error({title:"Hey",message:"Something wrong. Please try again!",position:"topRight"})})}
//# sourceMappingURL=index.js.map
