import{S as p,a as m,i as s}from"./assets/vendor-DY53avbb.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const d=new p(".gallery .gallery-link",{captionsData:"alt",captionDelay:250});function f(o){const r=o.map(({largeImageURL:i,webformatURL:n,tags:e,likes:t,views:a,comments:c,downloads:u})=>`<li class="gallery-item">
  <a class="gallery-link" href="${i}">
    <img class="gallery-image" src="${n}" alt="${e}"/>
  </a>
  <div class="info">
    <p class="info-item"><b>Likes</b><span>${t}</span></p>
    <p class="info-item"><b>Views</b> <span>${a}</span></p>
    <p class="info-item"><b>Comments</b> <span>${c}</span></p>
    <p class="info-item"><b>Downloads</b> <span>${u}</span></p>
  </div>
</li>`).join("");document.querySelector(".gallery").innerHTML=r,d.refresh()}function y(){document.querySelector(".gallery").innerHTML=""}function g(){document.querySelector(".loader-wrapper").classList.remove("is-hidden")}function l(){document.querySelector(".loader-wrapper").classList.add("is-hidden")}const h="56396197-05fcd5e3b9536b865c8ea6b88";function b(o){return m.get("https://pixabay.com/api/",{params:{key:h,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}})}const L={galleryEl:document.querySelector(".gallery"),formEl:document.querySelector(".form"),loaderEl:document.querySelector(".loader-wrapper")};L.formEl.addEventListener("submit",S);function S(o){o.preventDefault();const r=o.target.elements[0].value.trim();if(!r){s.show({title:"Caution",message:"Search field cannot be empty. Please enter a keyword!",position:"topRight"});return}y(),g(),b(r).then(i=>{if(l(),i.data.hits.length===0){s.error({title:"Sorry, ",message:"there are no images matching your search query. Please try again!",position:"topRight"});return}f(i.data.hits)}).catch(i=>{l(),s.error({title:"Hey",message:"Something wrong. Please try again!",position:"topRight"})})}
//# sourceMappingURL=index.js.map
