import{S as p,a as m,i as a}from"./assets/vendor-DY53avbb.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const d=new p(".gallery .gallery-link",{captionsData:"alt",captionDelay:250});function f(o){const r=o.map(({largeImageURL:i,webformatURL:s,tags:e,likes:t,views:n,comments:c,downloads:u})=>`<li class="gallery-item">
  <a class="gallery-link" href="${i}">
    <img class="gallery-image" src="${s}" alt="${e}"/>
  </a>
  <div class="info">
    <p class="info-item"><b>Likes</b><span>${t}</span></p>
    <p class="info-item"><b>Views</b> <span>${n}</span></p>
    <p class="info-item"><b>Comments</b> <span>${c}</span></p>
    <p class="info-item"><b>Downloads</b> <span>${u}</span></p>
  </div>
</li>`).join("");document.querySelector(".gallery").innerHTML=r,d.refresh()}function y(){document.querySelector(".gallery").innerHTML=""}function g(){document.querySelector(".loader-wrapper").classList.remove("is-hidden")}function l(){document.querySelector(".loader-wrapper").classList.add("is-hidden")}const h="56396197-05fcd5e3b9536b865c8ea6b88";function b(o){return m.get("https://pixabay.com/api/",{params:{key:h,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(r=>r.data)}const L={galleryEl:document.querySelector(".gallery"),formEl:document.querySelector(".form"),loaderEl:document.querySelector(".loader-wrapper")};L.formEl.addEventListener("submit",S);function S(o){o.preventDefault();const r=o.target.elements[0].value.trim();if(!r){a.show({title:"Caution",message:"Search field cannot be empty. Please enter a keyword!",position:"topRight"});return}y(),g(),b(r).then(i=>{if(l(),i.hits.length===0){a.error({title:"Sorry, ",message:"there are no images matching your search query. Please try again!",position:"topRight"});return}f(i.hits)}).catch(i=>{l(),a.error({title:"Hey",message:"Something wrong. Please try again!",position:"topRight"})})}
//# sourceMappingURL=index.js.map
